name: Parse and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0,5,10 6 * * *"

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.1"
          gleam-version: "1.4.1"
          rebar3-version: "3"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Download dependencies
        run: gleam deps download

      - name: Run script
        uses: nick-fields/retry@v3.0.0
        with:
          max_attempts: 3
          retry_wait_seconds: 15
          timeout_minutes: 2
          command: gleam run
        env:
          CHROBOT_BROWSER_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./priv/static
          publish_branch: gh-pages
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Update from GitHub Actions"
          cname: eczaneleri.guria.dev
