name: Parse and Deploy

on:
  workflow_call:
    inputs:
      chrome_path:
        required: true
        type: string

jobs:
  parse-and-deploy:
    runs-on: ${{ inputs.runner || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: gleam deps download

      - name: Run script
        uses: nick-fields/retry@v3.0.0
        with:
          max_attempts: 3
          retry_wait_seconds: 15
          timeout_minutes: 2
          command: gleam run
        env:
          CHROBOT_BROWSER_PATH: ${{ inputs.chrome_path }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./priv/static
          publish_branch: gh-pages
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Update from GitHub Actions"
          cname: eczaneleri.guria.dev
